# Generated by Django 5.1.7 on 2025-07-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=150)),
                ('eventdate', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
            ],
        ),
    ]
